version: "3"
services:
  backend-user:
    build:
      context: ./udagram-api-user
      dockerfile: Dockerfile
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    ports:
      - 8082:8082
  backend-feed:
    build:
      context: ./udagram-api-feed
      dockerfile: Dockerfile
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    ports:
      - 8081:8081
  udagram-frontend:
    depends_on:
      - backend-feed
      - backend-user
    build:
      context: ./udagram-frontend
      dockerfile: Dockerfile
    ports:
      - 8100:80
    tty: true
  reverseproxy:
    depends_on:
      - backend-feed
      - backend-user
    build:
      context: ./udagram-reverseproxy
      dockerfile: Dockerfile
    ports:
      - 8080:8080
