version: "3"
services:
  backend-user:
    build:
      context: ./udagram-api-user
      dockerfile: Dockerfile
    image: jflneves/backend-user
    environment:
      POSTGRES_USERNAME: udagramuser
      POSTGRES_PASSWORD: udagrampass
      POSTGRES_DB: udagramjflnevesdb
      POSTGRES_HOST: udagramjflnevesdb.cloknzutaws3.eu-central-1.rds.amazonaws.com
      AWS_REGION: eu-central-1
      AWS_PROFILE: test
      AWS_BUCKET: arn:aws:s3:::udagram-jflneves-bucket
      JWT_SECRET: testing
      URL: "http://localhost:8100"
    ports:
      - 8082:8082
  backend-feed:
    build:
      context: ./udagram-api-feed
      dockerfile: Dockerfile
    image: jflneves/backend-feed
    environment:
      POSTGRES_USERNAME: udagramuser
      POSTGRES_PASSWORD: udagrampass
      POSTGRES_DB: udagramjflnevesdb
      POSTGRES_HOST: udagramjflnevesdb.cloknzutaws3.eu-central-1.rds.amazonaws.com
      AWS_REGION: eu-central-1
      AWS_PROFILE: test
      AWS_BUCKET: arn:aws:s3:::udagram-jflneves-bucket
      JWT_SECRET: testing
      URL: "http://localhost:8100"
    ports:
      - 8081:8081
  udagram-frontend:
    depends_on:
      - backend-feed
      - backend-user
    build:
      context: ./udagram-frontend
      dockerfile: Dockerfile
    image: jflneves/udagram-frontend
    ports:
      - 8100:80
    tty: true
  reverseproxy:
    depends_on:
      - backend-feed
      - backend-user
    build:
      context: ./udagram-reverseproxy
      dockerfile: Dockerfile
    image: jflneves/reverseproxy
    ports:
      - 8080:8080
