apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    app: backend-user
