apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: backend-feed
